sudo: false
language: node_js
env:
  - APP_DIR=src
node_js:
  - 10
  - 12
  - 14
  - node
script:
  - yarn install --non-interactive
  - yarn lint
  - yarn test
jobs:
  include:
    - stage: deploy
      on:
        branch: master
      node_js: 14
      script:
        - yarn install --non-interactive
        - npx semantic-release
notifications:
  email:
    on_success: never
    on_failure: always
